# Generated by Django 5.2.15 on 2026-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_remove_job_requirements_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("reviewing", "Reviewing"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
