# Generated by Django 5.2.15 on 2026-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending", "Pending"),
                    ("Reviewing", "Reviewing"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
